# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests, with the NodeJS version specified in `.nvmrc`.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install-deps chromium
      - run: npx playwright install chromium
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run build
      - run: npm run test:integration
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
